apiVersion: apps/v1
kind: Deployment
metadata:
  name: sofa
  labels:
    app: sofa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sofa
  template:
    metadata:
      labels:
        app: sofa
    spec:
      containers:
      - name: sofa
        image: sofa:latest
        ports:
        - containerPort: 8080